project:
  type: website
  output-dir: _site

website:
  title: "marimo test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: chapters/linear-regression.py
        text: "01: Linear Regression"

format:
  html:
    theme: cosmo
    # This line is the "magic" that tells Quarto to use Marimo for .py files
    marimo: true 

# Ensure the extension is listed here
filters:
  - marimo